### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by ndowens** [necco889/CombatInsights#2]
https://imgur.com/a/2pOOWlo Been getting that while trying to use CI for my DK and sorc. Use to only happen maybe on one toon

**Comment by necco889** [comment]
could you check it again with the new version (1.1.2) please?

**Comment by ndowens** [comment]
I've tried on my Arcanist/Sorc/DK and so far it seems to work as expected

**Comment by necco889** [comment]
Cool, thanks again let me know if you find anything else :)
